name: Verify GPG Signature

on: [push, pull_request]

jobs:
  verify-signature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GPG directory
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
      - name: Import GPG Public Key
        run: |
          echo "${{ secrets.GPG_PUBLIC_KEY }}" | gpg --import
      - name: Verify commit signature
        run: |
          GPG_TTY=$(tty) git log --show-signature -1
        env:
          GPG_TTY: ${{ secrets.GPG_PUBLIC_KEY }}

      - name: Require signed commits
        run: |
          git config --global commit.gpgSign true


